---
- name: Configure net filter
  sysctl: name="net.ipv4.conf.all.rp_filter" value=0 sysctl_set=yes
- name: configure net filer
  sysctl: name="net.ipv4.conf.default.rp_filter" value=0 sysctl_set=yes
- name: Install neutron component on compute node
  apt: name={{ item }} state=present force=yes
  with_items:
    - neutron-plugin-openvswitch-agent
    - python-openstackclient
- name: Configure neutron on compute node
  template: src="neutron.conf.j2" dest="/etc/neutron/neutron.conf" mode=0644
  notify:
    - restart neutron-openvswitch-agent
- name: Configure openvswitch on compute node
  template: src="openvswitch_agent.ini.j2" dest="/etc/neutron/plugins/ml2/openvswitch_agent.ini" mode=0644
  notify:
    - restart neutron-openvswitch-agent
